stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/transactions.csv
      - data/hdb-resale-price-index.csv
    outs:
      - data/clean_data.csv

#  validate:
#    cmd: python validate_data.py data.csv
#    deps:
#      - data.csv
#      - validate_data.py
#    outs:
#      - validation_result.txt
  eda:
    cmd: python src/eda.py
    deps:
      - src/eda.py
      - data/clean_data.csv
    outs:
      - data/pandas_profiling_report.html

  train:
    cmd: python src/train.py
    deps:
      - data/clean_data.csv
      - src/train.py
    outs:
      - models/pipeline.pkl

  optimize:
    cmd: python src/optimize.py
    deps:
      - data/clean_data.csv
      - src/optimize.py
      - models/pipeline.pkl
    outs:
      - models/best_pipeline.pkl

  interpret:
    cmd: python src/interpret.py
    deps:
      - data/clean_data.csv
      - src/interpret.py
      - models/best_pipeline.pkl
    outs:
      - models/shap_summary_plot.png
      - models/explainer.pkl